const STATE_LEFT_WHEELS = 'l';
const STATE_RIGHT_WHEELS = 'r';
const STATE_CAMERA = 'c';
const STATE_LIGHTS = 'h';
const STATE_HONK = 'b';

const COMMAND_CAMERA = 'c';
const COMMAND_AXIS_X = 'x';
const COMMAND_AXIS_Y = 'y';
const COMMAND_SPEED = 's';
const COMMAND_HONK = 'h';
const COMMAND_LIGHTS = 'l';


module.exports = {
  STATE_LEFT_WHEELS,
  STATE_RIGHT_WHEELS,
  STATE_CAMERA,
  STATE_LIGHTS,
  STATE_HONK,

  COMMAND_CAMERA,
  COMMAND_AXIS_X,
  COMMAND_AXIS_Y,
  COMMAND_SPEED,
  COMMAND_HONK,
  COMMAND_LIGHTS,
};
